### ISSUE TITLE
Report on raytracer failing to start on windows system.

### ISSUE THREAD

**Issue by ghost** [kgabis/raytracer#2]
The problem occurs because Windows OS does not allow the naming of such file with the following characters: `\/:*?"<>|`. This bug was confirmed when I appended a short debugging code: `perror(filename);` at line 54: https://github.com/kgabis/raytracer/blob/2482567cfd9fa0406941f33819bc737f655e893c/raytracer/png_render.c#L54-L56

The output:
![Capture](https://user-images.githubusercontent.com/46589135/96836853-2556ab00-1478-11eb-95f4-3d05565caabb.PNG)

The solution I've made for this is to explicitly assign my own favorite name at fopen: `fopen("pizza.png", "wb");`

By the way, when try the demo, "teapot", raytracer completely crashes. Other demos (spheres, snowman), complete works.

For goodness sake...

**Comment by kgabis** [comment]
I'm not maintaining this project anymore, sorry.
